2021-07-27 11:27:57,565 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchStaticListAjax.html, match_id = 1470, half = 0
2021-07-27 11:27:57,565 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchStaticListAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157AD721F88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-27 11:28:38,681 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchDefencesRateAjax.html, match_id = 1513, half = 1
2021-07-27 11:28:38,681 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchDefencesRateAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157AD291248>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-27 11:29:47,433 - get_team_names.py[line:26] - WARNING: get team names failed: http://data.champdas.com/match/data-1662.html
2021-07-27 11:29:47,433 - get_team_names.py[line:27] - WARNING: 404 Client Error: Not Found for url: http://data.champdas.com/match/data-1662.html
